name: CI/CD Despliegue React a EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Compilar React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Compilar aplicación
        run: npm run build

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  deploy:
    name: Desplegar en EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Copiar archivos al servidor EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "/var/www/tic-tac-toe"

      - name: Reiniciar Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
